#
# Copyright (c) 2020 Bubble, Inc.  All rights reserved. For personal (non-commercial) use, see license: https://getbubblenow.com/bubble-license/
#
- name: Install OpenSSL, nginx and software-properties-common
  apt:
    name: [ 'openssl', 'nginx', 'software-properties-common' ]
    state: present
    update_cache: yes
  when: enable_nginx

- name: Enable Ubuntu universe repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
    - "deb http://archive.ubuntu.com/ubuntu/ focal universe"
    - "deb http://archive.ubuntu.com/ubuntu/ focal-updates universe"
    - "deb http://security.ubuntu.com/ubuntu/ focal-security universe"
  when: enable_nginx

- name: Install certbot
  apt:
    name: [ 'certbot', 'python3-certbot-nginx' ]
    state: present
    update_cache: yes
  when: enable_nginx

- name: Ensure nginx can read cert files
  file:
    dest: /etc/letsencrypt
    group: www-data
    recurse: yes
  when: enable_nginx

- name: Ensure nginx is stopped
  service:
    name: nginx
    state: stopped
  when: enable_nginx and packer_builder_type != 'docker'

- name: Install helper scripts
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: 0500
  with_items:
    - init_dhparams.sh
    - init_certbot.sh
  when: enable_nginx

# File in cron.weekly must NOT have a .sh extension, or crond will not run it
- name: Install certbot_renew.sh weekly cron job
  copy:
    src: "certbot_renew.sh"
    dest: /etc/cron.weekly/certbot_renew
    owner: root
    group: root
    mode: 0755
  when: enable_nginx

- name: Create server_names_hash_bucket_size nginx conf
  copy:
    src: server_names_hash_bucket_size.conf
    dest: /etc/nginx/conf.d/server_names_hash_bucket_size.conf
  when: enable_nginx

- name: Install init_dhparams supervisor conf file
  copy:
    src: supervisor_init_dhparams.conf
    dest: /etc/supervisor/conf.d/init_dhparams.conf
  when: enable_nginx
