ALTER TABLE received_notification ALTER COLUMN error TYPE VARCHAR(20100);
ALTER TABLE sent_notification ALTER COLUMN error TYPE VARCHAR(20100);
ALTER TABLE bubble_backup ALTER COLUMN error TYPE VARCHAR(20100);
