#
# Copyright (c) 2020 Bubble, Inc.  All rights reserved. For personal (non-commercial) use, see license: https://getbubblenow.com/bubble-license/
#
- name: Set the cert name
  shell: set_cert_name.sh /home/mitmproxy/mitmproxy {{ server_alias }}

- name: Reuse bubble mitm certs if available
  shell: reuse_bubble_mitm_certs.sh

- name: Copy bubble_config.py to /home/mitmproxy/mitmproxy
  template:
    src: bubble_config.py.j2
    dest: /home/mitmproxy/mitmproxy/bubble_config.py
    owner: mitmproxy
    group: mitmproxy
    mode: 0500

- name: Ensure mitmproxy user owns all mitmproxy files
  shell: chown -R mitmproxy /home/mitmproxy/mitmproxy

- import_tasks: route.yml

- name: Install supervisor conf file
  copy:
    src: supervisor_mitmproxy.conf
    dest: /etc/supervisor/conf.d/mitmproxy.conf
    owner: root
    group: root
    mode: 0400

- name: Install mitmdump_monitor supervisor conf file
  copy:
    src: supervisor_mitmdump_monitor.conf
    dest: /etc/supervisor/conf.d/mitmdump_monitor.conf

- name: restart supervisord
  service:
    name: supervisor
    enabled: yes
    state: restarted

- name: Ensure mitmdump_monitor is started
  shell: supervisorctl restart mitmdump_monitor
