- name: Install packages missing on docker ubuntu
  apt:
    name: [ 'curl', 'rsync', 'cron', 'iptables', 'redis', 'postgresql', 'supervisor' ]
    state: present
    update_cache: yes

# phusion daemon documentation: https://github.com/phusion/baseimage-docker#adding-additional-daemons
- name: Ensure /etc/service/ dirs exists
  file:
    path: "/etc/service/{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items: [ 'redis', 'postgresql', 'supervisor', 'cron' ]

- name: Create /etc/service/redis/run
  copy:
    src: run_redis.sh
    dest: /etc/service/redis/run
    owner: root
    group: root
    mode: 0755

- name: Ensure redis runs in foreground
  shell: bash -c "sed -i -e 's/daemonize yes/daemonize no/g' /etc/redis/redis.conf"

- name: Create /etc/service/postgresql/run
  copy:
    src: run_postgresql.sh
    dest: /etc/service/postgresql/run
    owner: root
    group: root
    mode: 0755

- name: trust local postgresql users
  shell: bash -c "sed -i -e 's/  md5/  trust/g' $(find /etc/postgresql -mindepth 1 -maxdepth 1 -type d | sort | tail -1)/main/pg_hba.conf"

- name: Create /etc/service/supervisor/run
  copy:
    src: run_supervisor.sh
    dest: /etc/service/supervisor/run
    owner: root
    group: root
    mode: 0755

- name: Create /etc/service/cron/run
  copy:
    src: run_cron.sh
    dest: /etc/service/cron/run
    owner: root
    group: root
    mode: 0755

# documented here: https://github.com/phusion/baseimage-docker#enabling-ssh
- name: Enable sshd
  shell: rm -f /etc/service/sshd/down
