#
# Copyright (c) 2020 Bubble, Inc.  All rights reserved. For personal (non-commercial) use, see license: https://getbubblenow.com/bubble-license/
#
- name: Set hostname to {{ hostname }}
  hostname:
    name: '{{ hostname }}'
  when: bubble_set_hostname == 'true'

- name: Set log flag to true with EX of 7 days for non-sage nodes
  shell: echo 'set bubble.StandardSelfNodeService.bubble_server_logs_enabled "true" EX 604800' | redis-cli
  when: install_type != 'sage'

- name: Set log flag to true with EX of 30 days for sage nodes
  shell: echo 'set bubble.StandardSelfNodeService.bubble_server_logs_enabled "true" EX 2592000' | redis-cli
  when: install_type == 'sage'
