# Things in {{CURLIES}} will be read from the process environment.
# Values are typically set in ${HOME}/.bubble.env

serverName: bubble-api

#publicUriBase: https://127.0.0.1
publicUriBase: {{PUBLIC_BASE_URI}}

defaultLocale: {{#exists BUBBLE_DEFAULT_LOCALE}}{{BUBBLE_DEFAULT_LOCALE}}{{else}}en_US{{/exists}}
testMode: {{#exists BUBBLE_TEST_MODE}}{{BUBBLE_TEST_MODE}}{{else}}false{{/exists}}

database:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://127.0.0.1:5432/bubble
  user: bubble
  password: '{{#exists BUBBLE_PG_PASSWORD}}{{BUBBLE_PG_PASSWORD}}{{else}}{{key_file '.BUBBLE_PG_PASSWORD'}}{{/exists}}'

  encryptionEnabled: true
  encryptionKey: '{{#exists BUBBLE_DB_ENCRYPTION_KEY}}{{BUBBLE_DB_ENCRYPTION_KEY}}{{else}}{{key_file '.BUBBLE_DB_ENCRYPTION_KEY'}}{{/exists}}'
  encryptorPoolSize: 50

  migrationEnabled: true

  hibernate:
    entityPackages:
    - bubble.model
    - org.cobbzilla.wizard.model.crypto   # for encrypted column support
    - org.cobbzilla.wizard.model.json     # for JSONB column support
    dialect: org.cobbzilla.wizard.model.json.JSONBPostgreSQLDialect
    showSql: {{#exists BUBBLE_SHOW_SQL}}{{BUBBLE_SHOW_SQL}}{{else}}false{{/exists}}
    hbm2ddlAuto: validate
    validationMode: ddl

staticAssets:
  baseUri: /
  assetRoot: site/
  utilPaths:
    INDEX_PATH: /index.html
    INDEX_ALIASES: /:/index.php

http:
  port: {{#exists BUBBLE_SERVER_PORT}}{{BUBBLE_SERVER_PORT}}{{else}}8090{{/exists}}
  baseUri: /api

jersey:
  resourcePackages:
   - bubble.resources
   - org.cobbzilla.wizard.server
   - org.cobbzilla.wizard.filters
  providerPackages:
   - org.cobbzilla.wizard.exceptionmappers
  requestFilters: [ bubble.auth.BubbleAuthFilter ]
  responseFilters:
   - org.cobbzilla.wizard.filters.ScrubbableScrubber
   - org.cobbzilla.wizard.filters.EntityTypeHeaderResponseFilter

redis:
  key: '{{#exists BUBBLE_REDIS_ENCRYPTION_KEY}}{{BUBBLE_REDIS_ENCRYPTION_KEY}}{{else}}{{key_file '.BUBBLE_REDIS_ENCRYPTION_KEY'}}{{/exists}}'
  prefix: bubble_

letsencryptEmail: {{LETSENCRYPT_EMAIL}}
localStorageDir: {{LOCALSTORAGE_BASE_DIR}}

disallowedCountries: {{DISALLOWED_COUNTRIES}}
paymentsEnabled: {{BUBBLE_PAYMENTS_ENABLED}}
