#
# Copyright (c) 2020 Bubble, Inc.  All rights reserved. For personal (non-commercial) use, see license: https://bubblev.com/bubble-license/
#
- name: Creates bubble SQL dir
  file:
    path: /home/bubble/sql
    owner: bubble
    group: postgres
    mode: 0550
    state: directory

- name: Install SQL schema files
  copy:
    src: "{{ item }}"
    dest: /home/bubble/sql/{{ item }}
    owner: bubble
    group: postgres
    mode: 0440
  with_items:
    - "bubble.sql.gz"

- name: Install DB initializer
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: postgres
    mode: 0550
  with_items:
    - init_bubble_db.sh

- name: Populate database
  shell: sudo -H -u postgres bash -c "cd && full_reset_db.sh"
