#
# Copyright (c) 2020 Bubble, Inc.  All rights reserved. For personal (non-commercial) use, see license: https://getbubblenow.com/bubble-license/
#
- name: Install PostgreSQL
  apt:
    name: [ 'postgresql-10', 'libpq-dev', 'python-psycopg2' ]
    state: present
    update_cache: yes

- name: Install PostgreSQL files
  copy:
    src: "{{ item }}"
    dest: /etc/postgresql/10/main/
    owner: postgres
    group: postgres
    mode: 0400
  with_items:
    - postgresql.conf
    - pg_hba.conf

# When PostgreSQL restarts after a reboot, for some weird reason it looks in the 9.4 dir (instead of 10) for files
- name: Symlink /var/lib/postgresql/9.4 -> /var/lib/postgresql/10
  file:
    src: /var/lib/postgresql/10
    dest: /var/lib/postgresql/9.4
    owner: root
    group: root
    state: link

- name: Symlink /etc/postgresql/9.4 -> /etc/postgresql/10
  file:
    src: /etc/postgresql/10
    dest: /etc/postgresql/9.4
    owner: root
    group: root
    state: link
