#
# Copyright (c) 2020 Bubble, Inc.  All rights reserved. For personal (non-commercial) use, see license: https://getbubblenow.com/bubble-license/
#
- name: Ensure nginx is stopped
  service:
    name: nginx
    state: stopped

- name: Create dhparam nginx conf
  template:
    src: stronger_dhparams.conf
    dest: /etc/nginx/conf.d/stronger_dhparams.conf

- include: site.yml

- name: Init certbot
  shell: init_certbot.sh {{ letsencrypt_email }} {{ server_name }} {{ server_alias }}
