#
# Copyright (c) 2020 Bubble, Inc.  All rights reserved. For personal (non-commercial) use, see license: https://getbubblenow.com/bubble-license/
#
- name: Snapshot ansible roles in the background
  command: bash -c "/usr/local/bin/snapshot_ansible.sh &"

- name: Create first-time setup file
  shell: su - bubble bash -c "echo -n install > /home/bubble/first_time_marker"
  when: restore_key is not defined

- name: Create first-time setup file (restore)
  shell: su - bubble bash -c "echo -n restore > /home/bubble/first_time_marker"
  when: restore_key is defined

- name: Install bubble supervisor conf file
  template:
    src: "supervisor_bubble.conf.j2"
    dest: /etc/supervisor/conf.d/bubble.conf

# Save 1% of memory, every bit counts on small nodes
- name: Disable peer manager on small nodes
  shell: |
    supervisorctl stop bubble_peer_manager || echo '[finalizer::main] WARNING: error stopping bubble_peer_manager' >> /var/log/bubble/ansible.log
    rm -f /etc/supervisor/conf.d/bubble_peer_manager.conf
  when: total_memory < 2048

- name: save iptables v4 rules
  shell: iptables-save > /etc/iptables/rules.v4
  become: yes

- name: save iptables v6 rules
  shell: ip6tables-save > /etc/iptables/rules.v6
  become: yes

- name: Restart iptables
  service:
    name: netfilter-persistent
    state: restarted

- name: Ensure nginx dhparams.pem file exists and is valid
  shell: /usr/local/bin/init_dhparams.sh wait
  when: enable_nginx

- name: Ensure nginx required files exist
  shell: /usr/local/bin/ensure_file_exists.sh {{ item }} 300
  with_items:
    - /etc/letsencrypt/live/{{ server_alias }}/fullchain.pem
    - /etc/letsencrypt/live/{{ server_name }}/fullchain.pem
  when: enable_nginx

- name: Ensure nginx is restarted
  service:
    name: nginx
    state: restarted
  when: enable_nginx

- name: stat /usr/share/unattended-upgrades/20auto-upgrades-disabled
  stat:
    path: /usr/share/unattended-upgrades/20auto-upgrades-disabled
  register: upgrades_disabled_file

- name: Enable unattended upgrades
  shell: systemctl start unattended-upgrades
  become: yes
  when: upgrades_disabled_file.stat.exists

- name: Ensure authorized SSH keys are up-to-date
  shell: su - bubble bash -c "touch /home/bubble/.refresh_ssh_keys"

- name: reload supervisord
  shell: |
    supervisorctl reload \
      || echo "[finalizer::main] WARNING: supervisorctl reload exited with $?" | tee -a /var/log/bubble/ansible.log \
      && sleep 10s && supervisorctl reload \
        || echo "[finalizer::main] WARNING: supervisorctl reload exited AGAIN with $?" | tee -a /var/log/bubble/ansible.log

- name: Install mitmproxy CA cert in local CA store
  shell: install_cert.sh /home/mitmproxy/.mitmproxy/{{ cert_name }}-ca-cert.pem 600
  when: install_type == 'node'

- name: Install mitmproxy public certs in bubble dir
  shell: /usr/local/bin/copy_certs_to_bubble.sh {{ cert_name }}
  when: install_type == 'node'
