#
# Copyright (c) 2020 Bubble, Inc.  All rights reserved. For personal (non-commercial) use, see license: https://getbubblenow.com/bubble-license/
#
- name: Snapshot ansible roles in the background
  command: bash -c "/usr/local/bin/snapshot_ansible.sh &"

- name: Create first-time setup file
  shell: su - bubble bash -c "echo -n install > /home/bubble/first_time_marker"
  when: restore_key is not defined

- name: Create first-time setup file (restore)
  shell: su - bubble bash -c "echo -n restore > /home/bubble/first_time_marker"
  when: restore_key is defined

- name: Install mitmproxy CA cert in local CA store
  shell: install_cert.sh /home/mitmproxy/.mitmproxy/{{ cert_name }}-ca-cert.pem 600
  when: install_type == 'node'

- name: Install mitmproxy public certs in bubble dir
  shell: /usr/local/bin/copy_certs_to_bubble.sh {{ cert_name }}
  when: install_type == 'node'

- name: Install bubble supervisor conf file
  template:
    src: "supervisor_bubble.conf.j2"
    dest: /etc/supervisor/conf.d/bubble.conf

- name: save iptables v4 rules
  shell: iptables-save > /etc/iptables/rules.v4
  become: yes

- name: save iptables v6 rules
  shell: ip6tables-save > /etc/iptables/rules.v6
  become: yes

- name: Restart iptables
  service:
    name: netfilter-persistent
    state: restarted

# We cannot receive notifications until nginx is running, so start bubble API as the very last step
- name: reload supervisord
  shell: supervisorctl reload

# dhparams file is created async. it takes a while and might not have finished. nginx will fail to start without it.
- name: Ensure dhparams.pem exists
  shell: /usr/local/bin/ensure_file_exists.sh /etc/nginx/dhparams.pem 300

- name: Ensure nginx is restarted
  service:
    name: nginx
    state: restarted

- name: Enable unattended upgrades
  shell: systemctl start unattended-upgrades
  become: yes

- name: Ensure authorized SSH keys are up-to-date
  shell: su - bubble bash -c "touch /home/bubble/.refresh_ssh_keys"
